_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 76
            "2":
                - 1
                - 11
                - 49
                - 55
                - 76
            "3":
                - 14
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.2
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
dropout:
    value: 0.3
k:
    value: 6
ngram:
    value: 5
